"""Types for signal generation."""

from dataclasses import dataclass
from datetime import datetime
from typing import Optional


@dataclass(frozen=True)
class SignalEvent:
    """A signal event generated by a strategy, formatted for console output."""

    timestamp: datetime
    symbol: str
    action: str  # "long", "short", "close"
    price: float
    reason: str
    strategy_name: str
    z_score: Optional[float] = None

    def __str__(self) -> str:
        ts = self.timestamp.strftime("%Y-%m-%d %H:%M:%S")
        action = self.action.upper().ljust(5)
        z = f" z={self.z_score:.2f}" if self.z_score is not None else ""
        return (
            f"[{ts}] {self.strategy_name} | "
            f"{self.symbol} {action} @ {self.price:.2f}{z} | "
            f"{self.reason}"
        )
